# Commit: Simplify Podfile to rely on Expo autolinking and modular headers
platform :ios, '15.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_modular_headers!

target 'BigFamFestival' do
  config = use_native_modules!

  # Expo managed dependencies and autolinked RN pods
  use_expo_modules!
  # Add React Native pods (Hermes enabled by default in Expo SDKs)
  use_react_native!(
    :path => '../node_modules/react-native'
  )

  post_install do |installer|
    react_native_post_install(installer)
    # Make UUIDs deterministic to reduce Xcode project UUID issues from merges
    installer.pods_project.use_deterministic_uuids = true
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
