name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint -- --fix
      
      - name: Type check
        run: npm run typecheck
      
      - name: Run tests
        run: npm test
  
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bigfam-repository/bigfam-backend:latest
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bigfam-repository/bigfam-backend:${{ github.sha }}
          cache-from: type=registry,ref=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bigfam-repository/bigfam-backend:buildcache
          cache-to: type=registry,ref=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bigfam-repository/bigfam-backend:buildcache,mode=max
  
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bigfam-api-production
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bigfam-repository/bigfam-backend:${{ github.sha }}
          region: us-central1
          env_vars: |
            NODE_ENV=production
            CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
          secrets: |
            JWT_SECRET=jwt-secret:latest
      
      - name: Output service URL
        run: echo "Service URL ${{ steps.deploy.outputs.url }}"
